program: scripts/finetune_cheetah.py
command:
  - ${env}
  - python
  - scripts/finetune_cheetah.py
method: bayes
metric:
  name: train/total_accumulated_loss
  goal: minimize
parameters:
  trainer_params.init_cov_scale:
    min: 0.0001
    max: 10.0
    distribution: log_uniform_values
